### PR TITLE
Grammar mistakes and issue fixes

### PR DESCRIPTION
**Pull request by itz-rj-here**

### CODE REVIEW

**Comment by tomkeuper** [comment]
Do you think we need an actual ico? Maybe something else than the BW2023 logo?

**Comment by tomkeuper** [comment]
lmk when its ready for a review btw, it looks good so far!

**Comment by itz-rj-here** [comment]
The png also works, as far as I know. 
If you want me to add the logo as an ico, I can add it.

**Comment by itz-rj-here** [comment]
but there is one issue 
the ico quality is not that much good 
So I prefer to use png instead.

**Comment by tomkeuper** [comment]
All good, we can also change it up at a later point

**Comment by itz-rj-here** [comment]
As you say.

**Comment by itz-rj-here** [comment]
@tomkeuper can you fix the maven shields.io https://shields.io/badges/sonatype-nexus-releases problem?
It shows that it couldn't find the version and the artifact.

**Comment by tomkeuper** [comment]
> @tomkeuper can you fix the maven shields.io https://shields.io/badges/sonatype-nexus-releases problem? It shows that it couldn't find the version and the artifact.

It seems that my repo doesnt have the bedwars artifact O-o

**Comment by itz-rj-here** [comment]
thats sad
then should i add the github version one?

**Comment by tomkeuper** [comment]
> thats sad then should i add the github version one?

No I will try to fix it now. Just dont look at the badge it will fix itself ones the repo is correct

**Comment by itz-rj-here** [comment]
As you say,
And my work is finished. Mention me if you see any problems or issues.

**Comment by itz-rj-here** [comment]
@tomkeuper requesting for a review.

**Review by tomkeuper — APPROVED** [review]

**Comment by tomkeuper** [comment]
Thank you for all the effort!!!

**Comment by itz-rj-here** [comment]
You're Welcome.

**Pull request merged**
